version: '2'
services:
    gt-auth:
      container_name: gt-auth
      image: node:8.12.0-alpine
      working_dir: /home/node/app
      volumes:
        - ./:/home/node/app
      mem_limit: 512mb
      memswap_limit: 512mb
      command: "npm start"
      environment:
        JWT_SECRET: 123
        DEBUG: express:*
        #NODE_ENV: 'production'
      network_mode: host      
    gt-auth-mongo-db:
      container_name: gt-auth-mongo-db
      image: aashreys/mongo-auth
      restart: always
      network_mode: host
      mem_limit: 512mb
      memswap_limit: 512mb      
      environment:
        MONGODB_ADMIN_USER: developer
        MONGODB_ADMIN_PASS: dev@123
        MONGODB_APPLICATION_DATABASE: gt-auth
        MONGODB_APPLICATION_USER: app
        MONGODB_APPLICATION_PASS: app@123
    gt-workspace
      container_name: gt-workspace
      image: node
      working_dir: /home/node/app
      volumes:
        - ./:/home/node/app
      mem_limit: 512mb
      memswap_limit: 512mb
